name: Build Flutter Web to /docs folder

on:
  push:
    branches: ["main-new"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get
        
      - name: Build web app in release mode
        run: |
          # Build dengan base-href yang tepat
          flutter build web --release --web-renderer html --base-href /jadwal_sholat_app/
          
      - name: Prepare docs directory
        run: |
          # Hapus direktori docs jika ada
          rm -rf docs
          # Buat direktori docs dan pindahkan hasil build ke sana
          mkdir -p docs
          cp -r build/web/* docs/
          
      - name: Verify docs directory
        run: |
          echo "Files in docs directory:"
          ls -la docs
          
          # Pastikan file-file penting ada
          if [ ! -f docs/index.html ] || [ ! -f docs/main.dart.js ]; then
            echo "Error: Critical files missing in docs directory!"
            exit 1
          fi
          
      - name: Commit and push to main branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs
          git commit -m "Update web app build in docs folder" || echo "No changes to commit"
          git push
